version: '3.8'

services:
  harrys:
    build: "./"
    restart: always
    container_name: harrys
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
    ports:
      - "6500:3000"
